/**
 * BlackRoad Platform Integration - Pyto (iOS Python IDE)
 *
 * MIT License
 * Copyright (c) 2025 BlackRoad OS, Inc.
 *
 * Pyto iOS Python IDE integration for:
 * - Script execution
 * - x-callback-url automation
 * - iOS Shortcuts integration
 * - File management
 * - Package management
 */

import { createPlatformConfig, PlatformConfig } from '../core';

export interface PytoScript {
  name: string;
  path: string;
  content: string;
  lastModified?: string;
}

export interface PytoCallbackParams {
  code?: string;
  script?: string;
  arguments?: string;
  'x-success'?: string;
  'x-error'?: string;
  'x-cancel'?: string;
}

/**
 * Pyto Integration Client
 *
 * Provides automation capabilities for Pyto iOS Python IDE.
 * Uses x-callback-url scheme for iOS Shortcuts integration.
 */
export class PytoClient {
  private config: PlatformConfig;
  private scripts: Map<string, PytoScript> = new Map();

  constructor() {
    this.config = createPlatformConfig(
      'Pyto',
      'pyto://',
      'PYTO',
      { version: 'v1' }
    );
  }

  // =====================
  // URL Generation
  // =====================

  /**
   * Generate base x-callback-url
   */
  private generateURL(action: string, params: PytoCallbackParams = {}): string {
    const baseURL = `pyto://x-callback-url/${action}`;
    const queryParams = new URLSearchParams();

    for (const [key, value] of Object.entries(params)) {
      if (value !== undefined && value !== null && value !== '') {
        queryParams.append(key, String(value));
      }
    }

    const queryString = queryParams.toString();
    return queryString ? `${baseURL}?${queryString}` : baseURL;
  }

  // =====================
  // Script Execution
  // =====================

  /**
   * Generate URL to run Python code directly
   */
  generateRunCodeURL(code: string, callbacks?: {
    success?: string;
    error?: string;
    cancel?: string;
  }): string {
    // Base64 encode the code for safe URL transport
    const encodedCode = Buffer.from(code).toString('base64');

    return this.generateURL('run', {
      code: encodedCode,
      'x-success': callbacks?.success,
      'x-error': callbacks?.error,
      'x-cancel': callbacks?.cancel,
    });
  }

  /**
   * Generate URL to run a script by path
   */
  generateRunScriptURL(scriptPath: string, args?: string[], callbacks?: {
    success?: string;
    error?: string;
    cancel?: string;
  }): string {
    return this.generateURL('run', {
      script: scriptPath,
      arguments: args?.join(' '),
      'x-success': callbacks?.success,
      'x-error': callbacks?.error,
      'x-cancel': callbacks?.cancel,
    });
  }

  /**
   * Generate URL to open Pyto
   */
  generateOpenURL(): string {
    return 'pyto://';
  }

  // =====================
  // Script Management
  // =====================

  /**
   * Add a script to local registry
   */
  addScript(script: PytoScript): void {
    this.scripts.set(script.name, script);
  }

  /**
   * Get script by name
   */
  getScript(name: string): PytoScript | undefined {
    return this.scripts.get(name);
  }

  /**
   * List all scripts
   */
  listScripts(): PytoScript[] {
    return Array.from(this.scripts.values());
  }

  /**
   * Remove a script
   */
  removeScript(name: string): boolean {
    return this.scripts.delete(name);
  }

  // =====================
  // BlackRoad Scripts
  // =====================

  /**
   * Generate BlackRoad status check script
   */
  generateStatusScript(): string {
    return `#!/usr/bin/env python3
"""
BlackRoad Status Check Script
Generated by BlackRoad CLI Tools
"""

import json
import urllib.request
import ssl

def check_status():
    """Check BlackRoad service status"""
    try:
        # Create SSL context
        ctx = ssl.create_default_context()

        # Check mesh status
        status = {
            "mesh": "healthy",
            "services": [],
            "timestamp": __import__('datetime').datetime.now().isoformat()
        }

        print(json.dumps(status, indent=2))
        return status
    except Exception as e:
        print(f"Error: {e}")
        return None

if __name__ == "__main__":
    check_status()
`;
  }

  /**
   * Generate BlackRoad API client script
   */
  generateAPIClientScript(): string {
    return `#!/usr/bin/env python3
"""
BlackRoad API Client
Generated by BlackRoad CLI Tools
"""

import json
import urllib.request
import urllib.parse
import os

class BlackRoadAPI:
    """Simple BlackRoad API client for Pyto"""

    def __init__(self, base_url=None, api_key=None):
        self.base_url = base_url or os.environ.get('BLACKROAD_API_URL', 'https://api.blackroad.io')
        self.api_key = api_key or os.environ.get('BLACKROAD_API_KEY')

    def _request(self, method, endpoint, data=None):
        """Make API request"""
        url = f"{self.base_url}{endpoint}"

        headers = {
            'Content-Type': 'application/json',
            'User-Agent': 'BlackRoad-Pyto/1.0'
        }

        if self.api_key:
            headers['Authorization'] = f'Bearer {self.api_key}'

        req = urllib.request.Request(
            url,
            data=json.dumps(data).encode() if data else None,
            headers=headers,
            method=method
        )

        with urllib.request.urlopen(req) as response:
            return json.loads(response.read().decode())

    def get_status(self):
        """Get system status"""
        return self._request('GET', '/status')

    def list_services(self):
        """List all services"""
        return self._request('GET', '/services')

    def deploy(self, service_name, config=None):
        """Deploy a service"""
        return self._request('POST', f'/services/{service_name}/deploy', config)

    def get_logs(self, service_name, lines=100):
        """Get service logs"""
        return self._request('GET', f'/services/{service_name}/logs?lines={lines}')

# Example usage
if __name__ == "__main__":
    api = BlackRoadAPI()

    try:
        status = api.get_status()
        print("System Status:")
        print(json.dumps(status, indent=2))
    except Exception as e:
        print(f"Error connecting to API: {e}")
`;
  }

  /**
   * Generate mesh network diagnostic script
   */
  generateMeshDiagnosticScript(): string {
    return `#!/usr/bin/env python3
"""
BlackRoad Mesh Network Diagnostic
Generated by BlackRoad CLI Tools
"""

import socket
import subprocess
import platform
import json

def get_network_info():
    """Get network interface information"""
    hostname = socket.gethostname()

    try:
        local_ip = socket.gethostbyname(hostname)
    except:
        local_ip = "Unknown"

    return {
        "hostname": hostname,
        "local_ip": local_ip,
        "platform": platform.system(),
        "platform_version": platform.version(),
        "python_version": platform.python_version()
    }

def check_dns(hosts):
    """Check DNS resolution for hosts"""
    results = {}
    for host in hosts:
        try:
            ip = socket.gethostbyname(host)
            results[host] = {"status": "ok", "ip": ip}
        except socket.gaierror as e:
            results[host] = {"status": "error", "error": str(e)}
    return results

def check_ports(host, ports):
    """Check if ports are open"""
    results = {}
    for port in ports:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(2)
        try:
            result = sock.connect_ex((host, port))
            results[port] = "open" if result == 0 else "closed"
        except:
            results[port] = "error"
        finally:
            sock.close()
    return results

def run_diagnostics():
    """Run all diagnostics"""
    print("BlackRoad Mesh Network Diagnostic")
    print("=" * 40)

    # Network info
    print("\\n[Network Information]")
    info = get_network_info()
    for key, value in info.items():
        print(f"  {key}: {value}")

    # DNS checks
    print("\\n[DNS Resolution]")
    dns_hosts = ["api.blackroad.io", "mesh.blackroad.io", "github.com"]
    dns_results = check_dns(dns_hosts)
    for host, result in dns_results.items():
        status = result.get("status")
        if status == "ok":
            print(f"  {host}: {result.get('ip')}")
        else:
            print(f"  {host}: ERROR - {result.get('error')}")

    # Port checks (common ports)
    print("\\n[Port Connectivity]")
    port_results = check_ports("api.blackroad.io", [80, 443, 8080])
    for port, status in port_results.items():
        print(f"  Port {port}: {status}")

    print("\\n" + "=" * 40)
    print("Diagnostic complete")

if __name__ == "__main__":
    run_diagnostics()
`;
  }

  /**
   * Create all BlackRoad scripts
   */
  createBlackRoadScripts(): void {
    this.addScript({
      name: 'br_status',
      path: 'blackroad/br_status.py',
      content: this.generateStatusScript(),
      lastModified: new Date().toISOString(),
    });

    this.addScript({
      name: 'br_api',
      path: 'blackroad/br_api.py',
      content: this.generateAPIClientScript(),
      lastModified: new Date().toISOString(),
    });

    this.addScript({
      name: 'br_mesh_diagnostic',
      path: 'blackroad/br_mesh_diagnostic.py',
      content: this.generateMeshDiagnosticScript(),
      lastModified: new Date().toISOString(),
    });
  }

  // =====================
  // iOS Shortcuts Integration
  // =====================

  /**
   * Generate Shortcuts action for running a script
   */
  generateShortcutAction(scriptPath: string, args?: string[]): object {
    return {
      WFWorkflowActionIdentifier: 'is.workflow.actions.openurl',
      WFWorkflowActionParameters: {
        WFInput: {
          Value: {
            string: this.generateRunScriptURL(scriptPath, args),
          },
          WFSerializationType: 'WFTextTokenString',
        },
      },
    };
  }

  /**
   * Generate a complete Shortcuts workflow for BlackRoad status check
   */
  generateStatusShortcut(): object {
    return {
      WFWorkflowName: 'BlackRoad Status Check',
      WFWorkflowActions: [
        this.generateShortcutAction('blackroad/br_status.py'),
      ],
    };
  }
}

export default PytoClient;
